### ISSUE TITLE
What about a variation of the Nord theme?

### ISSUE THREAD

**Issue by rodrigocfd** [GrayJack/monokai-grayjack-vscode#1]
This one:

* https://marketplace.visualstudio.com/items?itemName=arcticicestudio.nord-visual-studio-code

It looks easy on my tired eyes, but there are almost no semantic distinctions, particularly for Rust.

**Comment by GrayJack** [comment]
I added a Nord variant to the theme in the latest commit, check it out and see if you liked it 😄

**Comment by rodrigocfd** [comment]
It looks terrific, buddy.

Valeu mesmo.
